"""add_resume_exports

Revision ID: 16009aeeb3f9
Revises: 976202c6c2bc
Create Date: 2026-07-16 08:55:38.927546

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '16009aeeb3f9'
down_revision: str | Sequence[str] | None = '976202c6c2bc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_exports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('resume_version', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('renderer_version', sa.String(length=50), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_exports_checksum'), 'resume_exports', ['checksum'], unique=False)
    op.create_index(op.f('ix_resume_exports_resume_id'), 'resume_exports', ['resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_exports_resume_id'), table_name='resume_exports')
    op.drop_index(op.f('ix_resume_exports_checksum'), table_name='resume_exports')
    op.drop_table('resume_exports')
    # ### end Alembic commands ###
