"""create_evidence_audits_and_columns

Revision ID: 976202c6c2bc
Revises: 5ee97271c4f8
Create Date: 2026-07-16 08:35:49.255108

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '976202c6c2bc'
down_revision: str | Sequence[str] | None = '5ee97271c4f8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('resume_version', sa.Integer(), nullable=False),
    sa.Column('credibility_version', sa.String(length=50), nullable=False),
    sa.Column('evidence_state_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('raw_applicable_max', sa.Float(), nullable=False),
    sa.Column('claim_support_score', sa.Float(), nullable=False),
    sa.Column('internal_consistency_score', sa.Float(), nullable=False),
    sa.Column('career_profile_score', sa.Float(), nullable=False),
    sa.Column('high_risk_support_score', sa.Float(), nullable=False),
    sa.Column('transparency_score', sa.Float(), nullable=False),
    sa.Column('claim_count', sa.Integer(), nullable=False),
    sa.Column('contradiction_count', sa.Integer(), nullable=False),
    sa.Column('unsupported_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ai_fallback_active', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_audits_resume_id'), 'evidence_audits', ['resume_id'], unique=False)
    op.add_column('evidence_sources', sa.Column('contradiction_reason', sa.Text(), nullable=True))
    op.add_column('resume_claims', sa.Column('resume_version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('resume_claims', sa.Column('claim_type', sa.String(length=50), nullable=False, server_default='responsibility'))
    op.add_column('resume_claims', sa.Column('normalized_value', sa.String(length=255), nullable=False, server_default=''))
    op.add_column('resume_claims', sa.Column('field_name', sa.String(length=50), nullable=True))
    op.add_column('resume_claims', sa.Column('bullet_index', sa.Integer(), nullable=True))
    op.add_column('resume_claims', sa.Column('original_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_claims', 'original_text')
    op.drop_column('resume_claims', 'bullet_index')
    op.drop_column('resume_claims', 'field_name')
    op.drop_column('resume_claims', 'normalized_value')
    op.drop_column('resume_claims', 'claim_type')
    op.drop_column('resume_claims', 'resume_version')
    op.drop_column('evidence_sources', 'contradiction_reason')
    op.drop_index(op.f('ix_evidence_audits_resume_id'), table_name='evidence_audits')
    op.drop_table('evidence_audits')
    # ### end Alembic commands ###
