"""update_ai_suggestion_and_evidence_models

Revision ID: a37282f03a79
Revises: e3844a5eacc5
Create Date: 2026-07-15 13:26:51.902894

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.db.types import JSONBType

# revision identifiers, used by Alembic.
revision: str = 'a37282f03a79'
down_revision: str | Sequence[str] | None = 'e3844a5eacc5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_suggestions', sa.Column('match_result_id', sa.UUID(), nullable=True))
    op.add_column('ai_suggestions', sa.Column('source_resume_version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('ai_suggestions', sa.Column('target_section', sa.String(length=50), nullable=False, server_default='summary'))
    op.add_column('ai_suggestions', sa.Column('target_entry_id', sa.String(length=100), nullable=True))
    op.add_column('ai_suggestions', sa.Column('target_field', sa.String(length=50), nullable=False, server_default='content'))
    op.add_column('ai_suggestions', sa.Column('target_index', sa.Integer(), nullable=True))
    op.add_column('ai_suggestions', sa.Column('original_text', sa.Text(), nullable=False, server_default=''))
    op.add_column('ai_suggestions', sa.Column('suggested_text', sa.Text(), nullable=False, server_default=''))
    op.add_column('ai_suggestions', sa.Column('edited_text', sa.Text(), nullable=True))
    op.add_column('ai_suggestions', sa.Column('rationale', sa.Text(), nullable=True))
    op.add_column('ai_suggestions', sa.Column('risk_level', sa.String(length=50), nullable=False, server_default='low'))
    op.add_column('ai_suggestions', sa.Column('claim_validation', JSONBType(), nullable=False, server_default='[]'))
    op.add_column('ai_suggestions', sa.Column('expected_score_gain', sa.Integer(), nullable=True))
    op.add_column('ai_suggestions', sa.Column('provider_name', sa.String(length=50), nullable=True))
    op.add_column('ai_suggestions', sa.Column('model_name', sa.String(length=50), nullable=True))
    op.add_column('ai_suggestions', sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True))

    op.create_index(op.f('ix_ai_suggestions_match_result_id'), 'ai_suggestions', ['match_result_id'], unique=False)
    if op.get_context().dialect.name != 'sqlite':
        op.create_foreign_key('fk_ai_suggestions_match_result', 'ai_suggestions', 'job_match_results', ['match_result_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('ai_suggestions') as batch_op:
        batch_op.drop_column('original_content')
        batch_op.drop_column('suggested_content')
        batch_op.drop_column('confidence')
        batch_op.drop_column('verification_status')
        batch_op.drop_column('reasoning')
        batch_op.drop_column('section_type')
        batch_op.drop_column('section_entry_id')

    # Add columns to job_match_results
    op.add_column('job_match_results', sa.Column('potential_match_percentage', sa.Integer(), nullable=False, server_default='0'))

    # Add columns to evidence_sources
    op.add_column('evidence_sources', sa.Column('source_id', sa.String(length=100), nullable=True))
    op.add_column('evidence_sources', sa.Column('source_section', sa.String(length=50), nullable=True))
    op.add_column('evidence_sources', sa.Column('source_entry_id', sa.String(length=100), nullable=True))
    op.add_column('evidence_sources', sa.Column('source_field', sa.String(length=50), nullable=True))
    op.add_column('evidence_sources', sa.Column('excerpt', sa.Text(), nullable=True))
    op.add_column('evidence_sources', sa.Column('evidence_strength', sa.String(length=50), nullable=False, server_default='contextual'))
    op.add_column('evidence_sources', sa.Column('support_kind', sa.String(length=50), nullable=False, server_default='relevance_context'))
    op.add_column('evidence_sources', sa.Column('verification_status', sa.String(length=50), nullable=True))

    with op.batch_alter_table('evidence_sources') as batch_op:
        batch_op.drop_column('evidence_excerpt')
        batch_op.drop_column('source_reference')
        batch_op.drop_column('verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_sources', sa.Column('verified', sa.BOOLEAN(), nullable=False, server_default='0'))
    op.add_column('evidence_sources', sa.Column('source_reference', sa.VARCHAR(length=255), nullable=True))
    op.add_column('evidence_sources', sa.Column('evidence_excerpt', sa.TEXT(), nullable=True))

    with op.batch_alter_table('evidence_sources') as batch_op:
        batch_op.drop_column('verification_status')
        batch_op.drop_column('support_kind')
        batch_op.drop_column('evidence_strength')
        batch_op.drop_column('excerpt')
        batch_op.drop_column('source_field')
        batch_op.drop_column('source_entry_id')
        batch_op.drop_column('source_section')
        batch_op.drop_column('source_id')

    op.drop_column('job_match_results', 'potential_match_percentage')

    op.add_column('ai_suggestions', sa.Column('section_entry_id', sa.VARCHAR(length=100), nullable=True))
    op.add_column('ai_suggestions', sa.Column('section_type', sa.VARCHAR(length=50), nullable=False, server_default='summary'))
    op.add_column('ai_suggestions', sa.Column('reasoning', sa.TEXT(), nullable=True))
    op.add_column('ai_suggestions', sa.Column('verification_status', sa.VARCHAR(length=50), nullable=False, server_default='unverified'))
    op.add_column('ai_suggestions', sa.Column('confidence', sa.FLOAT(), nullable=False, server_default='0.0'))
    op.add_column('ai_suggestions', sa.Column('suggested_content', sa.TEXT(), nullable=False, server_default=''))
    op.add_column('ai_suggestions', sa.Column('original_content', sa.TEXT(), nullable=False, server_default=''))

    if op.get_context().dialect.name != 'sqlite':
        op.drop_constraint('fk_ai_suggestions_match_result', 'ai_suggestions', type_='foreignkey')
    op.drop_index(op.f('ix_ai_suggestions_match_result_id'), table_name='ai_suggestions')

    with op.batch_alter_table('ai_suggestions') as batch_op:
        batch_op.drop_column('applied_at')
        batch_op.drop_column('model_name')
        batch_op.drop_column('provider_name')
        batch_op.drop_column('expected_score_gain')
        batch_op.drop_column('claim_validation')
        batch_op.drop_column('risk_level')
        batch_op.drop_column('rationale')
        batch_op.drop_column('edited_text')
        batch_op.drop_column('suggested_text')
        batch_op.drop_column('original_text')
        batch_op.drop_column('target_index')
        batch_op.drop_column('target_field')
        batch_op.drop_column('target_entry_id')
        batch_op.drop_column('target_section')
        batch_op.drop_column('source_resume_version')
        batch_op.drop_column('match_result_id')
    # ### end Alembic commands ###
