"use client";

import { useState, useEffect } from "react";
import { Plus, MailOpen, FileText, Send, Loader2, Download, Trash2, Edit2, Check } from "lucide-react";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { coverLettersAPI, resumesAPI } from "@/lib/api";
import { toast } from "sonner";

interface CoverLetter {
  id: string;
  resume_id: string;
  title: string;
  content: string;
  export_path?: string;
  version: number;
}

export default function CoverLettersPage() {
  const [resumes, setResumes] = useState<any[]>([]);
  const [coverLetters, setCoverLetters] = useState<CoverLetter[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [selectedLetter, setSelectedLetter] = useState<CoverLetter | null>(null);

  // Generation forms
  const [selectedResumeId, setSelectedResumeId] = useState("");
  const [jobDescriptionText, setJobDescriptionText] = useState("");
  const [stylePreference, setStylePreference] = useState("professional");
  const [generatedDraft, setGeneratedDraft] = useState("");
  const [draftTitle, setDraftTitle] = useState("My Cover Letter");

  const [editingContent, setEditingContent] = useState("");
  const [editingTitle, setEditingTitle] = useState("");
  const [isEditing, setIsEditing] = useState(false);

  const fetchData = async () => {
    try {
      setLoading(true);
      const [resList, clList] = await Promise.all([
        resumesAPI.list(),
        coverLettersAPI.list()
      ]);
      setResumes(resList);
      setCoverLetters(clList);
      if (resList.length > 0) {
        setSelectedResumeId(resList[0].id);
      }
    } catch (err) {
      toast.error("Failed to load cover letters.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedResumeId || !jobDescriptionText) {
      toast.error("Please select a resume and paste the job description.");
      return;
    }
    try {
      setGenerating(true);
      const res = await coverLettersAPI.generate({
        resume_id: selectedResumeId,
        job_description_text: jobDescriptionText,
        style_preference: stylePreference,
      });
      setGeneratedDraft(res.content);
      toast.success("Cover letter generated by AI!");
    } catch (err) {
      toast.error("Failed to generate cover letter.");
    } finally {
      setGenerating(false);
    }
  };

  const handleSaveDraft = async () => {
    if (!generatedDraft) return;
    try {
      const payload = {
        resume_id: selectedResumeId,
        title: draftTitle || "Google Cover Letter",
        content: generatedDraft,
      };
      const created = await coverLettersAPI.create(payload);
      toast.success("Cover letter saved!");
      setGeneratedDraft("");
      setJobDescriptionText("");
      fetchData();
      setSelectedLetter(created);
    } catch (err) {
      toast.error("Failed to save cover letter.");
    }
  };

  const handleSaveEdit = async () => {
    if (!selectedLetter) return;
    try {
      const updated = await coverLettersAPI.update(
        selectedLetter.id,
        editingContent,
        editingTitle
      );
      toast.success("Cover letter saved!");
      setIsEditing(false);
      setSelectedLetter(updated);
      fetchData();
    } catch (err) {
      toast.error("Failed to update cover letter.");
    }
  };

  const handleVersionIncrement = async () => {
    if (!selectedLetter) return;
    try {
      const updated = await coverLettersAPI.incrementVersion(
        selectedLetter.id,
        editingContent,
        editingTitle
      );
      toast.success(`Incremented to Version ${updated.version}!`);
      setIsEditing(false);
      setSelectedLetter(updated);
      fetchData();
    } catch (err) {
      toast.error("Failed to create new version.");
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm("Delete this cover letter?")) return;
    try {
      await coverLettersAPI.delete(id);
      toast.success("Deleted.");
      setSelectedLetter(null);
      fetchData();
    } catch (err) {
      toast.error("Failed to delete cover letter.");
    }
  };

  const handleExportPDF = async (letter: CoverLetter) => {
    try {
      toast.loading("Exporting PDF...", { id: "export" });
      const res = await coverLettersAPI.exportPdf(letter.id);
      toast.success("PDF generated successfully!", { id: "export" });
      window.open(`http://localhost:8000/api/v1/cover-letters/${letter.id}/export`, "_blank");
      fetchData();
    } catch (err) {
      toast.error("PDF export failed.", { id: "export" });
    }
  };

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      <div>
        <h1 className="text-3xl font-extrabold tracking-tight text-foreground bg-gradient-to-r from-violet-500 to-indigo-500 bg-clip-text text-transparent">
          AI Cover Letter Generator
        </h1>
        <p className="text-muted-foreground mt-1">
          Craft hyper-tailored cover letters matching target job descriptions.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Form column */}
        <div className="lg:col-span-1 space-y-6">
          <Card className="border border-border">
            <CardHeader>
              <CardTitle className="text-lg">Create Cover Letter</CardTitle>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleGenerate} className="space-y-4">
                <div className="space-y-2">
                  <label className="text-sm font-semibold">Select Resume Profile</label>
                  <select
                    value={selectedResumeId}
                    onChange={(e) => setSelectedResumeId(e.target.value)}
                    className="w-full bg-input rounded-md border border-border px-3 py-2 text-sm text-foreground bg-transparent"
                  >
                    {resumes.map((r) => (
                      <option key={r.id} value={r.id}>
                        {r.title} (v{r.version})
                      </option>
                    ))}
                  </select>
                </div>

                <div className="space-y-2">
                  <label className="text-sm font-semibold">Target Job Description</label>
                  <Textarea
                    placeholder="Paste the Job Description here..."
                    rows={6}
                    value={jobDescriptionText}
                    onChange={(e) => setJobDescriptionText(e.target.value)}
                    required
                  />
                </div>

                <div className="space-y-2">
                  <label className="text-sm font-semibold">Style / Tone</label>
                  <select
                    value={stylePreference}
                    onChange={(e) => setStylePreference(e.target.value)}
                    className="w-full bg-input rounded-md border border-border px-3 py-2 text-sm text-foreground bg-transparent"
                  >
                    <option value="professional">Professional & Direct</option>
                    <option value="enthusiastic">Enthusiastic & Passionate</option>
                    <option value="creative">Creative & Narrative</option>
                    <option value="technical">Highly Technical & Analytical</option>
                  </select>
                </div>

                <Button type="submit" className="w-full" disabled={generating}>
                  {generating ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" /> Generating...
                    </>
                  ) : (
                    <>
                      <Send className="w-4 h-4 mr-2" /> Generate Cover Letter
                    </>
                  )}
                </Button>
              </form>
            </CardContent>
          </Card>

          <Card className="border border-border">
            <CardHeader>
              <CardTitle className="text-lg">Saved Letters</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              {coverLetters.length === 0 ? (
                <div className="text-center text-xs text-muted-foreground py-6">
                  No cover letters generated yet.
                </div>
              ) : (
                coverLetters.map((cl) => (
                  <div
                    key={cl.id}
                    onClick={() => {
                      setSelectedLetter(cl);
                      setEditingContent(cl.content);
                      setEditingTitle(cl.title);
                      setIsEditing(false);
                      setGeneratedDraft("");
                    }}
                    className={`p-3 rounded-lg border text-sm cursor-pointer hover:bg-muted/30 transition-all ${
                      selectedLetter?.id === cl.id ? "border-primary bg-primary-subtle text-primary" : "border-border"
                    }`}
                  >
                    <div className="font-bold flex items-center justify-between">
                      <span className="truncate">{cl.title}</span>
                      <Badge variant="secondary">v{cl.version}</Badge>
                    </div>
                  </div>
                ))
              )}
            </CardContent>
          </Card>
        </div>

        {/* Right Draft / Editor column */}
        <div className="lg:col-span-2 space-y-6">
          {generatedDraft ? (
            <Card className="border-2 border-primary bg-primary-subtle/5">
              <CardHeader className="flex flex-row items-center justify-between">
                <CardTitle className="text-lg flex items-center gap-2 text-primary">
                  <MailOpen className="w-5 h-5" /> Generated Draft
                </CardTitle>
                <div className="flex gap-2">
                  <Input
                    className="w-48 bg-card h-8 text-xs font-semibold"
                    value={draftTitle}
                    onChange={(e) => setDraftTitle(e.target.value)}
                    placeholder="Enter Title..."
                  />
                  <Button size="sm" onClick={handleSaveDraft}>
                    Save Draft
                  </Button>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="bg-card border border-border p-5 rounded-lg font-mono text-sm leading-relaxed whitespace-pre-wrap">
                  {generatedDraft}
                </div>
              </CardContent>
            </Card>
          ) : selectedLetter ? (
            <Card className="border border-border">
              <CardHeader className="flex flex-row items-center justify-between">
                <CardTitle className="text-lg">
                  {isEditing ? (
                    <Input
                      className="text-lg font-bold"
                      value={editingTitle}
                      onChange={(e) => setEditingTitle(e.target.value)}
                    />
                  ) : (
                    <span>
                      {selectedLetter.title}{" "}
                      <Badge variant="outline" className="ml-2">
                        v{selectedLetter.version}
                      </Badge>
                    </span>
                  )}
                </CardTitle>
                <div className="flex items-center gap-2">
                  {isEditing ? (
                    <>
                      <Button variant="ghost" size="sm" onClick={() => setIsEditing(false)}>
                        Cancel
                      </Button>
                      <Button variant="outline" size="sm" onClick={handleSaveEdit}>
                        Save (v{selectedLetter.version})
                      </Button>
                      <Button size="sm" onClick={handleVersionIncrement}>
                        Save as v{selectedLetter.version + 1}
                      </Button>
                    </>
                  ) : (
                    <>
                      <Button variant="outline" size="sm" onClick={() => setIsEditing(true)}>
                        <Edit2 className="w-3.5 h-3.5 mr-1" /> Edit
                      </Button>
                      <Button variant="secondary" size="sm" onClick={() => handleExportPDF(selectedLetter)}>
                        <Download className="w-3.5 h-3.5 mr-1" /> Export PDF
                      </Button>
                      <Button variant="ghost" size="sm" onClick={() => handleDelete(selectedLetter.id)}>
                        <Trash2 className="w-3.5 h-3.5 text-destructive" />
                      </Button>
                    </>
                  )}
                </div>
              </CardHeader>
              <CardContent>
                {isEditing ? (
                  <Textarea
                    className="font-mono text-sm leading-relaxed"
                    rows={20}
                    value={editingContent}
                    onChange={(e) => setEditingContent(e.target.value)}
                  />
                ) : (
                  <div className="bg-muted/10 border border-border p-5 rounded-lg font-mono text-sm leading-relaxed whitespace-pre-wrap">
                    {selectedLetter.content}
                  </div>
                )}
              </CardContent>
            </Card>
          ) : (
            <div className="h-96 border border-dashed border-border rounded-xl flex flex-col items-center justify-center text-center text-muted-foreground p-6 bg-card/10 backdrop-blur-md">
              <MailOpen className="w-12 h-12 text-muted-foreground/60 mb-3" />
              <h3 className="font-bold text-foreground text-lg">No letter selected</h3>
              <p className="max-w-xs text-xs mt-1">
                Generate a new custom cover letter draft or click a saved one to edit, preview, and print.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
